[project]
name = "test-tasks-2025"
version = "0.1.0"
description = "IMEI checker with TG bot"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "aiogram>=3.17.0",
    "environs>=14.1.0",
    "httpx>=0.28.1",
]
