services_data = [
    {"id": 1, "title": "Apple Basic Info", "price": "0.06"},
    {"id": 2, "title": "Apple Advanced Info", "price": "0.12"},
    {"id": 3, "title": "Apple Full Info (with MDM)", "price": "0.90"},
    {"id": 17, "title": "Apple Carrier + SIM-Lock Status", "price": "0.06"},
    {"id": 18, "title": "Apple Find My On/Off Status", "price": "0.01"},
    {"id": 19, "title": "Apple Sold By + Country", "price": "2.00"},
    {"id": 5, "title": "Samsung Info", "price": "0.10"},
    {"id": 4, "title": "LG Info", "price": "0.10"},
    {"id": 6, "title": "Xiaomi Info", "price": "0.10"},
    {"id": 7, "title": "OnePlus Info", "price": "0.04"},
    {"id": 8, "title": "Motorola Info", "price": "0.08"},
    {"id": 9, "title": "ZTE Info", "price": "0.05"},
    {"id": 10, "title": "Google Pixel Info", "price": "0.12"},
    {"id": 11, "title": "Huawei Info", "price": "0.10"},
    {"id": 16, "title": "Blacklist Pro Check (All IMEIs)", "price": "0.10"},
    {"id": 20, "title": "Convert IMEI ⇄ IMEI2 ⇄ Serial", "price": "0.02"},
    {"id": 21, "title": "Convert IMEI ⇄ IMEI2 ⇄ EID", "price": "0.05"},
    {"id": 22, "title": "Model + Brand + Manufacturer (by IMEI)", "price": "0.01"},
    {"id": 23, "title": "SIM-Lock Status", "price": "0.03"},
    {"id": 24, "title": "Model/Product Description", "price": "0.03"},
    {"id": 25, "title": "Warranty Check", "price": "0.02"},
    {"id": 26, "title": "Full GSX Report", "price": "2.20"},
    {"id": 27, "title": "GSX Cases + Repairs", "price": "1.99"},
]
